name: Build with Appflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master bran
on:
  push:
    branches: [ main ]

jobs:
  # This will build an IPA & Upload the artifact in iOS.zip
  # This will build an APK & Upload the artifact in Android.zip
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Build Android with Appflow
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.APPFLOW_TOKEN }}
          app-id: 9f2bd9ea
          platform: Android
          build-type: debug

  # This will trigger a live upda
