name: Build with Appflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

jobs:
  # This will build an IPA & Upload the artifact in iOS.zip
  build-ios:
    runs-on: ubuntu-latest
    steps:
      - name: Build iOS with Appflow
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.APPFLOW_TOKEN }}
          app-id: 9f2bd9ea
          platform: android
          build-type: debug
          build-stack: Linux - 2021.10
